apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vault-oss-backup.fullname" . }}-approle
  labels:
    {{- include "vault-oss-backup.labels" . | nindent 4 }}
type: Opaque
data:
  VAULT_APPROLE_ROLE_ID: {{ .Values.approle.roleId | b64enc | quote }}
  VAULT_APPROLE_SECRET_ID: {{ .Values.approle.secretId | b64enc | quote }}
  VAULT_APPROLE_AUTH_PATH: {{ .Values.approle.authPath | b64enc | quote }}