apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vault-oss-backup.fullname" . }}-minio
  labels:
    {{- include "vault-oss-backup.labels" . | nindent 4 }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.minio.accessKeyId | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.minio.secretAccesskey | b64enc | quote }}
  AWS_DEFAULT_REGION: {{ .Values.minio.region | b64enc | quote }}
  MINIO_URL: {{ .Values.minio.url | b64enc | quote }}
  MINIO_BUCKET_NAME: {{ .Values.minio.bucketName | b64enc | quote }}
  MINIO_BACKUP_FILENAME: {{ .Values.minio.backupFilename | default .Release.Name | b64enc | quote }}
